### ISSUE TITLE
Question: vscodium+netcoredbg?

### ISSUE THREAD

**Issue by Novack** [chickensoft-games/GameDemo#15]
Hello there Joanna, this repo looks so handy, I just grabed some vscode config files :) Thanks a ton!

Im wondering if you have tried a similar setup but using VSCodium? The debugger provided with Microsoft's C# extension is highly restrictive, licensed only to work with the official vscode build. A workaround for debugging C# projects in vscodium is to use Samsung's opensource [netcoredbg](https://github.com/Samsung/netcoredbg) package.

Do you, or anyone of your knowledge was able to make such setup work for Godot C# projects?

**Comment by Novack** [comment]
This is awesome, thanks a ton for the info. I've joined the discord, will close this issue now.

**Comment by granitrocky** [comment]
Here's a PR on the VSCodium C# extension that would enable this:

https://github.com/muhammadsammy/free-vscode-csharp/pull/68

**Comment by GeneralProtectionFault** [comment]
Looks like that just got merged  =D.
I tried grabbing & building the .vsix (following the process dgokcin used in that issue ^^^), installed it, and tried the launch.json examples graniterocky put in the same PR (in Godot).

It launched, which it wouldn't have done before the extension update, but it didn't hit a breakpoint.  Also, the game itself didn't "really" launch.  Very strange, it launches the *editor*--so I have 2 Godot editors open, but not the *game*.  In the editor that opened up from VS Codium, I see this:

```
--- Debug adapter server started ---
--- GDScript language server started on port 6005 ---
Add Autoload
[LSP] Connection Taken
```

Don't really care about the GDScript LOL, but I can't interact/click/etc... with this instance of the editor...so just somehow the game isn't fully launched, not sure what's going on there.

I just used the vanilla C# tasks.json:
```
{
          "label": "build",
          "group": "build",
          "type": "shell",
          "command": "dotnet",
          "args": [
            "build",
            "/property:GenerateFullPaths=true",
            "/consoleloggerparameters:NoSummary"
          ],
          "problemMatcher": "$msCompile"
}
```

For clarity on on Linux (Garuda).

**Comment by GeneralProtectionFault** [comment]
@definitelyokay Sure, like I said, I just used what graniterocky put in the PR you linked above (https://github.com/muhammadsammy/free-vscode-csharp/pull/72) -- except remove "-e" from the pipe args, that opens the Godot editor instead of running the project.  Also, the debug arguments I put in here are Godot's and are not necessary.  I assume you'd just put any relevant arguments for running Godot there if there are any.

```
"configurations": [
        {
            "name": "🕹 Run/Debug Game",
            "type": "coreclr",
            "request": "launch",
            "preLaunchTask": "build",
            "program": "",
            "cwd": "${workspaceFolder}",
            "internalConsoleOptions": "openOnSessionStart",
            "pipeTransport": {
                "pipeCwd": "${workspaceFolder}",
                "pipeProgram": "/usr/bin/godot",
                "pipeArgs": [
                  "--debug",
                  "--breakpoints"
                ]
            }
        }
    ]
```
